from typing import Protocol


class PasswordHasher(Protocol):
    def hash(self, plain_password: str) -> str: ...
    def verify(self, plain_password: str, password_hash: str) -> bool: ...


class TokenService(Protocol):
    def create_access_token(self, subject: str) -> str: ...
    def decode_subject(self, token: str) -> str: ...
